%%=======================================================================%%
%          Graphical User Interface for Chile Water resources project
%                             Version 4/4/2014
%%=======================================================================%%

%==========================================================================
%               Begin initialization code - DO NOT EDIT
%==========================================================================
function varargout = Debug(varargin)
clc
disp('===========================================');
disp('Initializing Graphical User Interface (GUI)');
disp('===========================================');
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @Debug_OpeningFcn, ...
                   'gui_OutputFcn',  @Debug_OutputFcn, ...
                   'gui_LayoutFcn',  @Debug_LayoutFcn, ...
                   'gui_Callback',   []);
    if nargin && ischar(varargin{1})
        gui_State.gui_Callback = str2func(varargin{1});
    end

    if  nargout
        [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
    else
        gui_mainfcn(gui_State, varargin{:});
    end

% Executes just before Debug is made visible.
    function Debug_OpeningFcn(hObject, eventdata, handles, varargin)
    handles.output = hObject;
    guidata(hObject, handles);

% Outputs from this function are returned to the command line.
    function varargout = Debug_OutputFcn(hObject, eventdata, handles) 
    varargout{1} = handles.output;

%==========================================================================
%                  Begin Defining Fields and buttons
%==========================================================================

%%=====================Root=============================%%%
function Root_Callback(hObject, eventdata, handles)
function Root_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%=================BASIN================%%
function Basin_Callback(hObject, eventdata, handles)
function Basin_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
     set(hObject,'BackgroundColor','white');
end


%%=======================Year====================%%
function Year_Callback(hObject, eventdata, handles)
function Year_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%=====================PROCESS DGA DOWNLOADS==========================%%
% --- Executes on button press that depicts "Process DGA Downloads".
function ProcessDGA_Callback(hObject, eventdata, handles) 
  Root = get(handles.Root, 'String');
  basin = get(handles.Basin, 'String'); 
  year = str2num(get(handles.Year, 'String')); 
  TotalDischarge(Root,basin,year);         
  AvgTemp(Root,basin,year);        
  AvgPrecip(Root,basin,year); 

%%=======================CREATE MASTER============================%%
%this creates master files for the Root basin and year that are inputed
function createMaster_Callback(hObject, eventdata, handles)
Root = get(handles.Root, 'String');
basin = get(handles.Basin, 'String'); 
year = str2num(get(handles.Year, 'String')); 
CreateMaster(Root,basin,year);

%%=====================EREF TEXTBOX========================%%
function Eref_Callback(hObject, eventdata, handles)
function Eref_CreateFcn(hObject, eventdata, handles)

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%========================BASE FLOW TEXTBOX=============================%%
function baseFlowTxt_Callback(hObject, eventdata, handles)
function baseFlowTxt_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%======================TLAG PERCIPITATION TEXTBOX=======================%%
function TlagPercipTxt_Callback(hObject, eventdata, handles)
function TlagPercipTxt_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%==========================TLAG SNOWMELT TEXTBOX========================%%
function TlagSnowmelt_Callback(hObject, eventdata, handles)
function TlagSnowmelt_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%=================RUNOFF COEFFICIENT SNOW TEXTBOX=======================%%
function runoffCoefSnow_Callback(hObject, eventdata, handles)
function runoffCoefSnow_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%===============Runoff Coefficient Percip from NASA TEXTBOX=============%%
function RCPn_Callback(hObject, eventdata, handles)
function RCPn_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%========================RCPS TEXTBOX=======================%%
function RCPs_Callback(hObject, eventdata, handles)
function RCPs_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%============================HYPSO BUTTON==============================%%
%should get the Root and basin text and call the Hyso script
function Hypso_Callback(hObject, eventdata, handles) 
root = get(handles.Root, 'String');
basin = get(handles.Basin, 'String'); 
Hypso(root,basin);

%===================CREATE PROFILES===================================%%
%will get the textbox information that it needs (including the start and
%end years and then create profiles for those years
function createProfiles_Callback(hObject, eventdata, handles)
Root = get(handles.Root, 'String');
basin = get(handles.Basin, 'String'); 
Years = str2num(get(handles.ProfileYears, 'String')); 
Create_Profiles(Root,basin,Years);

%=============Create Profiles First Year Textbox========================%
function ProfileYears_Callback(hObject, eventdata, handles)
function ProfileYears_CreateFcn(hObject, eventdata, handles)   
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%=======================CREATE MULTIYEAR MASTER========================%%
%creates a multiyear master when pushed for the years inputted into the
%textbox
function multiyearMaster_Callback(hObject, eventdata, handles)
    root = get(handles.Root, 'String');
    basin = get(handles.Basin, 'String'); 
    startYear = str2num(get(handles.Year0, 'String')); 
    endYear = str2num(get(handles.Year1, 'String')); 
    Years = startYear:endYear; 
    Create_MultiYear_Master(root,basin,Years);
    
%%=======================CREATE forecasted Master========================%%    
function CreateForecastedMaster_Callback(hObject, eventdata, handles)
    Root = get(handles.Root, 'String');
    basin = get(handles.Basin, 'String'); 
    year = str2num(get(handles.MasterToForecast, 'String'));     
    FZS = str2num(get(handles.JulianForecastStart, 'String')); 
    FZW = str2num(get(handles.ForecastRange, 'String')); 
    %execute PredictSnow using the start date text box value
    ForecastSnow(Root,basin,year,FZS,FZW,'n'); 
    
%%========================Forecast Button (Predicar de dia)===============%%
function RunForecast_Callback(hObject, eventdata, handles)
%Get the input values from the text boxes
    Root = get(handles.Root, 'String');
    basin = get(handles.Basin, 'String'); 
    year = str2num(get(handles.MasterToForecast, 'String'));
    ERef = str2num(get(handles.Eref, 'String'));  
    baseFlow = str2num(get(handles.baseFlowTxt, 'String')); 
    TimelagS = str2num(get(handles.TlagSnowmelt , 'String')) ; 
    TimelagP = str2num(get(handles.TlagPercipTxt, 'String'));
    DegDayF = str2num(get(handles.DegreeDayText, 'String')); 
    RCsnowF = str2num(get(handles.runoffCoefSnow, 'String')); 
    RCPsF = str2num(get(handles.RCPs, 'String'));
    RCPnF = str2num(get(handles.RCPn, 'String'));
    TlapseF = str2num(get(handles.TempLapseText, 'String')); 
    Tcrit = str2num(get(handles.TcritText, 'String'));
    Pthresh= str2num(get(handles.Precip_Threshold,'String'));
    XF = str2num(get(handles.XCoef, 'String')); 
    YF = str2num(get(handles.YCoef, 'String')); 
    
    if (get(handles.Save_Predict,'Value') == get(handles.Save_Predict,'Max'))
        Save =1;
    else
        Save=0;
    end
    
    FZS = str2num(get(handles.JulianForecastStart, 'String')); 
    FZW = str2num(get(handles.ForecastRange, 'String')); 
    TZW = str2num(get(handles.TuneZoneWidthF, 'String'));;
  
    if length(Root)==0 | length(basin) == 0 | length(year) == 0 | ...
         length(ERef) == 0 | length(baseFlow) == 0 | ...
         length(TimelagS) == 0 | length(TimelagP) == 0
     disp('An input is missing! Check root, basin, and year inputs'); 
    else
     [TuneError,ProjError]=DEVELOP_SRM(Root,basin,year,...
            TimelagS,TimelagP,ERef,baseFlow,'Project',DegDayF,RCsnowF,RCPsF,...
    RCPnF,TlapseF,XF,YF,Tcrit,Pthresh,Save,FZS,FZW,TZW);
    end
       
%Start Date used for the forecasting button
function JulianForecastStart_Callback(hObject, eventdata, handles)
function JulianForecastStart_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%Year to forecast
function MasterToForecast_Callback(hObject, eventdata, handles)
function MasterToForecast_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%%===========================SIMULATE BUTTON============================%%
function RunValidate_Callback(hObject, eventdata, handles)
    root = get(handles.Root, 'String');
    basin = get(handles.Basin, 'String'); 
    year = str2num(get(handles.MasterToSimulate, 'String')); 
    ERef = str2num(get(handles.Eref, 'String'));  
    baseFlow = str2num(get(handles.baseFlowTxt, 'String')); 
    TimelagS = str2num(get(handles.TlagSnowmelt , 'String')) ; 
    TimelagP = str2num(get(handles.TlagPercipTxt, 'String'));
    DegDayF = str2num(get(handles.DegreeDayText, 'String')); 
    RCsnowF = str2num(get(handles.runoffCoefSnow, 'String')); 
    RCPsF = str2num(get(handles.RCPs, 'String'));
    RCPnF = str2num(get(handles.RCPn, 'String'));
    TlapseF = str2num(get(handles.TempLapseText, 'String')); 
    Tcrit = str2num(get(handles.TcritText, 'String')); 
    Pthresh= str2num(get(handles.Precip_Threshold,'String'));
    XF = str2num(get(handles.XCoef, 'String')); 
    YF = str2num(get(handles.YCoef, 'String')); 
    
    FZS = str2num(get(handles.ForecastZoneStart, 'String')); 
    FZW = str2num(get(handles.ForecastZoneWidth, 'String')); 
    TZW = str2num(get(handles.TuneZoneWidthS, 'String')); 
    
    if (get(handles.Save_Simulate,'Value') == get(handles.Save_Simulate,'Max'))
        Save =1;
    else
        Save=0;
    end
  
    if length(root)==0 | length(basin) == 0 | length(year) == 0 | ...
         length(ERef) == 0 | length(baseFlow) == 0 | ...
         length(TimelagS) == 0 | length(TimelagP) == 0
     disp('An input is missing! Check root, basin, and year inputs'); 
    else
     [TuneError,ProjError]=DEVELOP_SRM(root,basin,year,...
            TimelagS,TimelagP,ERef,baseFlow,'Validate',DegDayF,RCsnowF,RCPsF,...
    RCPnF,TlapseF,XF,YF,Tcrit,Pthresh,Save,FZS,FZW,TZW);
    end
    
%%==================CALCULAR CUBIERTA DE NIEVE BUTTON====================%%
function snowCoveredArea_Callback(hObject, eventdata, handles)
    root = get(handles.Root, 'String');
    basin = get(handles.Basin, 'String'); 
    year = str2num(get(handles.MasterToForecast, 'String')); 
    SnowCoveredArea(root,basin,year);

%%==================MISC fields====================%%    
function Year0_Callback(hObject, eventdata, handles)
function Year0_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function Year1_Callback(hObject, eventdata, handles)
function Year1_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function DegreeDayText_Callback(hObject, eventdata, handles)
function DegreeDayText_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function TempLapseText_Callback(hObject, eventdata, handles)
function TempLapseText_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function XCoef_Callback(hObject, eventdata, handles)
function XCoef_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function YCoef_Callback(hObject, eventdata, handles)
function YCoef_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function Precip_Threshold_Callback(hObject, eventdata, handles)
function Precip_Threshold_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function TcritText_Callback(hObject, eventdata, handles)
function TcritText_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function MasterToSimulate_Callback(hObject, eventdata, handles)
function MasterToSimulate_CreateFcn(hObject, eventdata, handles)

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function edit45_Callback(hObject, eventdata, handles)
function edit45_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function ForecastRange_Callback(hObject, eventdata, handles)
function ForecastRange_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function ForecastZoneWidth_Callback(hObject, eventdata, handles)
function ForecastZoneWidth_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function TuneZoneWidthS_Callback(hObject, eventdata, handles)
function TuneZoneWidthS_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function TuneZoneWidthF_Callback(hObject, eventdata, handles)
function TuneZoneWidthF_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function ForecastZoneStart_Callback(hObject, eventdata, handles)
function ForecastZoneStart_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on button press in Save_Predict.
function Save_Predict_Callback(hObject, eventdata, handles)

% --- Executes on button press in Save_Simulate.
function Save_Simulate_Callback(hObject, eventdata, handles)
  


% --- Creates and returns a handle to the GUI figure. 
function h1 = Debug_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'edit', 53, ...
    'checkbox', 11, ...
    'text', 78, ...
    'radiobutton', 6, ...
    'pushbutton', 10, ...
    'uipanel', 8, ...
    'uitable', 3, ...
    'listbox', 3), ...
    'override', 0, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\Users\jwely\NASA_DEVELOP_TESTBED\Ejecutables\Matlab\Debug.m', ...
    'lastFilename', 'C:\Users\jwely\NASA_DEVELOP_TESTBED\Ejecutables\Matlab\GUI_English.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','GUI_English',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[103.8 3.30769230769231 145.6 59.3846153846154],...
'Resize','off',...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Title','Tuning Factors',...
'Clipping','on',...
'Position',[73.6000000000001 19.0769230769231 70.8 39],...
'Tag','uipanel1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h3 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 34.2307692307693 25 1.53846153846154],...
'String','Base Flow:',...
'Style','text',...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text7';

h4 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 31.7692307692308 35.6 1.53846153846154],...
'String','Max Time Lag (Precip):',...
'Style','text',...
'Tag','text7',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text6';

h5 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 29.4615384615385 49.8 1.38461538461538],...
'String','Max Time Lag (Snow):',...
'Style','text',...
'Tag','text6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text10';

h6 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11.5,...
'HorizontalAlignment','left',...
'Position',[1.8 26.5384615384616 43.8 1.38461538461538],...
'String','Runoff Coefficients: ',...
'Style','text',...
'Tag','text10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text11';

h7 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[9.8 21.923076923077 37.8 1.61538461538462],...
'String','Precipitation (TRMM, GPM):',...
'Style','text',...
'Tag','text11',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text9';

h8 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[9.8 17.3846153846154 29.4 1.38461538461538],...
'String','Precipitation (In-Situ):',...
'Style','text',...
'Tag','text9',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'baseFlowTxt';

h9 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('baseFlowTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.6 33.923076923077 10 2.15384615384615],...
'String','870',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('baseFlowTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','baseFlowTxt');

appdata = [];
appdata.lastValidTag = 'TlagPercipTxt';

h10 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TlagPercipTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.8 31.4615384615385 9.8 2.15384615384615],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TlagPercipTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TlagPercipTxt');

appdata = [];
appdata.lastValidTag = 'TlagSnowmelt';

h11 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TlagSnowmelt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.8 29.0769230769231 9.8 2.07692307692308],...
'String','1',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TlagSnowmelt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TlagSnowmelt');

appdata = [];
appdata.lastValidTag = 'runoffCoefSnow';

h12 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('runoffCoefSnow_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[47.4 24.0769230769231 10.8 2.15384615384615],...
'String','1.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('runoffCoefSnow_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','runoffCoefSnow');

appdata = [];
appdata.lastValidTag = 'RCPn';

h13 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('RCPn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[47.4 21.6923076923077 10.8 2.15384615384615],...
'String','1.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('RCPn_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','RCPn');

appdata = [];
appdata.lastValidTag = 'RCPs';

h14 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('RCPs_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[47.4 16.9230769230769 10.8 2.15384615384615],...
'String','1.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('RCPs_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','RCPs');

appdata = [];
appdata.lastValidTag = 'text18';

h15 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49 34.3076923076924 20.4 1.53846153846154],...
'String','(Liters/s)',...
'Style','text',...
'Tag','text18',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text19';

h16 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49 31.923076923077 20.4 1.53846153846154],...
'String','Days',...
'Style','text',...
'Tag','text19',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text20';

h17 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49 29.4615384615385 20.4 1.53846153846154],...
'String','Days',...
'Style','text',...
'Tag','text20',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text21';

h18 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[58.6 24.4615384615385 10.6 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text21',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text22';

h19 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[9.8 24.3846153846154 21.6 1.38461538461538],...
'String','Snow: ',...
'Style','text',...
'Tag','text22',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text24';

h20 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[58.6 17.0769230769231 8.8 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text24',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text25';

h21 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[58.6 21.8461538461539 10.2 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text25',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text31';

h22 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 13.3076923076923 29.4 1.38461538461538],...
'String','Degree-Day Factor:',...
'Style','text',...
'Tag','text31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text32';

h23 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 10.8461538461539 29.4 1.38461538461538],...
'String','Temp Lapse Factor:',...
'Style','text',...
'Tag','text32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text33';

h24 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[11.4 3.69230769230769 19 1.38461538461538],...
'String','X Coef:',...
'Style','text',...
'Tag','text33',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text34';

h25 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[11.4 1.38461538461538 17.8 1.38461538461538],...
'String','Y Coef:',...
'Style','text',...
'Tag','text34',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text36';

h26 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11.5,...
'HorizontalAlignment','left',...
'Position',[2 5.84615384615385 37 1.38461538461538],...
'String','Recession Coefficient: ',...
'Style','text',...
'Tag','text36',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DegreeDayText';

h27 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('DegreeDayText_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.6 12.8461538461539 10 2.15384615384615],...
'String','1.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('DegreeDayText_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','DegreeDayText');

appdata = [];
appdata.lastValidTag = 'TempLapseText';

h28 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TempLapseText_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.6 10.4615384615385 10 2.15384615384615],...
'String','1.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TempLapseText_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TempLapseText');

appdata = [];
appdata.lastValidTag = 'XCoef';

h29 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('XCoef_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'Position',[47.4 3.38461538461539 10.6 2.15384615384615],...
'String','0.95',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('XCoef_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','XCoef');

appdata = [];
appdata.lastValidTag = 'YCoef';

h30 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('YCoef_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[47.4 0.846153846153846 10.6 2.15384615384615],...
'String','0.05',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('YCoef_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','YCoef');

appdata = [];
appdata.lastValidTag = 'text52';

h31 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[16.2 19.6923076923077 29.4 1.38461538461538],...
'String','TRMM Zone:',...
'Style','text',...
'Tag','text52',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Precip_Threshold';

h32 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Precip_Threshold_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[47.4 19.3076923076923 10.8 2.15384615384615],...
'String','5',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Precip_Threshold_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Precip_Threshold');

appdata = [];
appdata.lastValidTag = 'text54';

h33 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49.6 13.1538461538462 11 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text54',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text55';

h34 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49.6 10.6923076923077 10.2 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text55',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text56';

h35 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[59 3.46153846153846 9.2 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text56',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text57';

h36 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[59.4 1 8.6 1.53846153846154],...
'String','Factor',...
'Style','text',...
'Tag','text57',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text58';

h37 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[59 19.4615384615385 9.6 1.53846153846154],...
'String','Zone #',...
'Style','text',...
'Tag','text58',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text59';

h38 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',11,...
'HorizontalAlignment','left',...
'Position',[2 8.53846153846154 28.6 1.38461538461538],...
'String','Critical Temperature:',...
'Style','text',...
'Tag','text59',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'TcritText';

h39 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TcritText_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38.8 8.07692307692309 10 2.15384615384615],...
'String','0.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TcritText_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TcritText');

appdata = [];
appdata.lastValidTag = 'text60';

h40 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontSize',9,...
'HorizontalAlignment','left',...
'Position',[49.6 8.30769230769231 14.8 1.53846153846154],...
'String','Degrees C',...
'Style','text',...
'Tag','text60',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel2';

h41 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Title','Prepare Inputs',...
'Clipping','on',...
'Position',[0.8 19.1538461538462 72.6 38.9230769230769],...
'Tag','uipanel2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text1';

h42 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[3 9.76923076923077 34.4 1.69230769230769],...
'String','Multi-Year Functions:',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'createMaster';

h43 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('createMaster_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',11,...
'Position',[10.8 12.8461538461538 48.2 2.61538461538462],...
'String','Create Master',...
'Tag','createMaster',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ProcessDGA';

h44 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('ProcessDGA_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',11,...
'Position',[10.8 18.6153846153846 48.2 2.69230769230769],...
'String','Process DGA Downloads',...
'Tag','ProcessDGA',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Year';

h45 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Year_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[23.2 21.6923076923077 14 2.07692307692308],...
'String','2011',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Year_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Year');

appdata = [];
appdata.lastValidTag = 'text2';

h46 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Position',[2.4 34.6923076923077 10.4 1.61538461538462],...
'String','Root:',...
'Style','text',...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h47 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Position',[2.4 32.4615384615385 13 1.61538461538462],...
'String','Basin: ',...
'Style','text',...
'Tag','text3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text4';

h48 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'Position',[10.2 21.6153846153846 8.8 1.84615384615385],...
'String','Year:',...
'Style','text',...
'Tag','text4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Hypso';

h49 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('Hypso_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',11,...
'Position',[13.6 29.1538461538462 55.4 2.61538461538462],...
'String','Characterize Basin Elevation Statistics',...
'Tag','Hypso',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'createProfiles';

h50 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('createProfiles_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',11,...
'Position',[3.4 6.92307692307692 37.4 2.30769230769231],...
'String','Create Profiles',...
'Tag','createProfiles',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ProfileYears';

h51 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('ProfileYears_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',9,...
'Position',[42.8 7.15384615384615 27.8 1.76923076923077],...
'String','[2003,2004,2005]',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('ProfileYears_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','ProfileYears');

appdata = [];
appdata.lastValidTag = 'multiyearMaster';

h52 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('multiyearMaster_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',11,...
'Position',[3.4 3.07692307692308 37.2 2.38461538461538],...
'String','Create Multiyear Master',...
'UserData',[],...
'Tag','multiyearMaster',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Year0';

h53 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Year0_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',9,...
'Position',[42.8 3.30769230769231 11.6 1.76923076923077],...
'String','2003',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Year0_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Year0');

appdata = [];
appdata.lastValidTag = 'text15';

h54 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',13,...
'Position',[54.6 3.53846153846154 4.2 1.53846153846154],...
'String','-',...
'Style','text',...
'Tag','text15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Year1';

h55 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Year1_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',9,...
'Position',[59.2 3.38461538461539 11.2 1.76923076923077],...
'String','2011',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Year1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Year1');

appdata = [];
appdata.lastValidTag = 'text29';

h56 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[3.2 23.9230769230769 45.8 1.69230769230769],...
'String','Prepare Inputs for One Year:',...
'Style','text',...
'Tag','text29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'snowCoveredArea';

h57 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('snowCoveredArea_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',11,...
'Position',[10.8 15.6153846153846 48.2 2.76923076923077],...
'String','Compute Snow Covered Area',...
'Tag','snowCoveredArea',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text65';

h58 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'FontSize',12,...
'Position',[2.6 27.1538461538462 30.2 1.38461538461538],...
'String','Reference Elevation:',...
'Style','text',...
'Tag','text65',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Eref';

h59 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('edit45_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[35.4 26.9230769230769 12.6 1.69230769230769],...
'String','1240',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('edit45_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Eref');

appdata = [];
appdata.lastValidTag = 'Root';

h60 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Root_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[15.8 34.6153846153846 53.6 1.84615384615385],...
'String','C:\Users\jwely\NASA_DEVELOP_TESTBED',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Root_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Root');

appdata = [];
appdata.lastValidTag = 'text76';

h61 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[50.6000000000001 5.84615384615385 20 1.15384615384615],...
'String','List of Years',...
'Style','text',...
'Tag','text76',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text77';

h62 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[46.8000000000002 2.07692307692308 20.4 1.15384615384615],...
'String','Start and End Years',...
'Style','text',...
'Tag','text77',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Basin';

h63 = uicontrol(...
'Parent',h41,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('Basin_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[15.8 32.2307692307692 53.2 1.76923076923077],...
'String','Coquimbo_Limari',...
'Style','edit',...
'Value',1,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('Basin_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Basin');

appdata = [];
appdata.lastValidTag = 'uipanel5';

h64 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Title','Simulate and Validate',...
'Clipping','on',...
'Position',[73.6 4.15384615384615 70.6 14.1538461538462],...
'Tag','uipanel5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'RunValidate';

h65 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('RunValidate_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10,...
'Position',[1.6 0.692307692307692 66.6 2.76923076923077],...
'String','Simulate ',...
'Tag','RunValidate',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text61';

h66 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[2.8 10.5384615384615 30.4 1.69230769230769],...
'String','Master to Simulate:',...
'Style','text',...
'UserData',[],...
'Tag','text61',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MasterToSimulate';

h67 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('MasterToSimulate_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'Position',[32.2 10.6153846153846 16 1.69230769230769],...
'String','2011',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('MasterToSimulate_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','MasterToSimulate');

appdata = [];
appdata.lastValidTag = 'Save_Simulate';

h68 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('Save_Simulate_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[50.4000000000001 10.6153846153846 18.6 1.76923076923077],...
'String','Output to File',...
'Style','checkbox',...
'Tag','Save_Simulate',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ForecastZoneWidth';

h69 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('ForecastZoneWidth_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38 4 10.2 1.69230769230769],...
'String','95',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('ForecastZoneWidth_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','ForecastZoneWidth');

appdata = [];
appdata.lastValidTag = 'text68';

h70 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[3 7.69230769230769 30.2 1.84615384615385],...
'String','Tuning Zone Width:',...
'Style','text',...
'UserData',[],...
'Tag','text68',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text69';

h71 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[3 3.92307692307692 31.8 1.69230769230769],...
'String','Forecast Zone Width:',...
'Style','text',...
'UserData',[],...
'Tag','text69',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'TuneZoneWidthS';

h72 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TuneZoneWidthS_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38 7.84615384615385 10.2 1.69230769230769],...
'String','120',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TuneZoneWidthS_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TuneZoneWidthS');

appdata = [];
appdata.lastValidTag = 'text70';

h73 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[49.0000000000001 8 11.2 1.15384615384615],...
'String','Days',...
'Style','text',...
'Tag','text70',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text71';

h74 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[49.2 4.30769230769231 11.2 1.15384615384615],...
'String','Days',...
'Style','text',...
'Tag','text71',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text74';

h75 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[3 5.69230769230769 30.2 1.84615384615385],...
'String','Forecast Zone Start:',...
'Style','text',...
'UserData',[],...
'Tag','text74',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ForecastZoneStart';

h76 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('ForecastZoneStart_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[38 5.92307692307692 10.2 1.69230769230769],...
'String','270',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('ForecastZoneStart_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','ForecastZoneStart');

appdata = [];
appdata.lastValidTag = 'text75';

h77 = uicontrol(...
'Parent',h64,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[49.0000000000001 6.07692307692308 11.2 1.15384615384615],...
'String','Julian Day',...
'Style','text',...
'Tag','text75',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel6';

h78 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',12,...
'FontWeight','bold',...
'Title','Forecast',...
'UserData',[],...
'Clipping','on',...
'Position',[0.8 4.15384615384616 65 14.1538461538462],...
'Tag','uipanel6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'RunForecast';

h79 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('RunForecast_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',10,...
'Position',[40.6 0.615384615384615 22 2.76923076923077],...
'String','Simulate',...
'UserData',[],...
'Tag','RunForecast',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'JulianForecastStart';

h80 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('JulianForecastStart_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'Position',[33.4000000000001 6 10 1.69230769230769],...
'String','270',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('JulianForecastStart_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','JulianForecastStart');

appdata = [];
appdata.lastValidTag = 'text48';

h81 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[2.2 6.00000000000001 22.2 1.69230769230769],...
'String','Forecast Start:',...
'Style','text',...
'UserData',[],...
'Tag','text48',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text49';

h82 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[2.2 10.6153846153846 39.4 1.69230769230769],...
'String','Master to Predict:',...
'Style','text',...
'UserData',[],...
'Tag','text49',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MasterToForecast';

h83 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('MasterToForecast_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'Position',[28.4 10.6923076923077 15 1.69230769230769],...
'String','2011',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('MasterToForecast_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','MasterToForecast');

appdata = [];
appdata.lastValidTag = 'text51';

h84 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[46.6 6.15384615384616 11.2 1.15384615384615],...
'String','Julian Day',...
'Style','text',...
'Tag','text51',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Save_Predict';

h85 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('Save_Predict_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[44.8 10.6153846153846 18.6 1.84615384615385],...
'String','Output to File',...
'Style','checkbox',...
'Tag','Save_Predict',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ForecastRange';

h86 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('ForecastRange_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'Position',[33.4000000000001 4.07692307692308 10 1.69230769230769],...
'String','95',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('ForecastRange_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'UserData',[],...
'Tag','ForecastRange');

appdata = [];
appdata.lastValidTag = 'text66';

h87 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[2.2 4.07692307692307 24.6 1.69230769230769],...
'String','Forecast Range:',...
'Style','text',...
'UserData',[],...
'Tag','text66',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text67';

h88 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[46.8 4.46153846153846 11.2 1.15384615384615],...
'String','Days',...
'Style','text',...
'Tag','text67',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text72';

h89 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'CData',[],...
'FontSize',12,...
'HorizontalAlignment','left',...
'Position',[2 7.6923076923077 30.2 1.84615384615385],...
'String','Tuning Zone Width:',...
'Style','text',...
'UserData',[],...
'Tag','text72',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'TuneZoneWidthF';

h90 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Debug('TuneZoneWidthF_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[33.4000000000001 7.92307692307692 10 1.69230769230769],...
'String','120',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Debug('TuneZoneWidthF_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','TuneZoneWidthF');

appdata = [];
appdata.lastValidTag = 'text73';

h91 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'HorizontalAlignment','left',...
'Position',[46.6000000000001 8.15384615384617 11.2 1.15384615384615],...
'String','Days',...
'Style','text',...
'Tag','text73',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CreateForecastedMaster';

h92 = uicontrol(...
'Parent',h78,...
'Units','characters',...
'Callback',@(hObject,eventdata)Debug('CreateForecastedMaster_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',10,...
'Position',[2 0.615384615384615 37 2.76923076923077],...
'String','Create Forecasted Master',...
'UserData',[],...
'Tag','CreateForecastedMaster',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text63';

h93 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontSize',16,...
'Position',[-0.2 1.30769230769231 95.6 2.38461538461538],...
'String','Tool created by NASA DEVELOP in Spring 2014.',...
'Style','text',...
'Tag','text63',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text64';

h94 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[0.600000000000001 0.461538461538463 33.6 1.15384615384615],...
'String','Contact: Jeff.Ely.08@gmail.com',...
'Style','text',...
'Tag','text64',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % DEBUG
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % DEBUG(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % DEBUG('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % DEBUG(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'GUIDEFigure');
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);  
    %workaround for CreateFcn not called to create ActiveX
    if feature('HGUsingMATLABClasses')
        peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
        for i=1:length(peers)
            if isappdata(peers(i),'Control')
                actxproxy(peers(i));
            end            
        end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


